version: '3'
services:
  treasureNet_productiondatauploader:
    image: treasurenet/productiondatauploader:1.0
    network_mode: "host"
    restart: unless-stopped
    container_name: productiondatauploader
    environment:
      - MONGO_URL=mongodb+srv://treasureNet:Lf7bZVPpArjyru9O@tnclusterm20.a9fcq.mongodb.net/treasureNet?retryWrites=true&w=majority
      - EVM_ENDPOINT=http://node1.testnet.treasurenet.io:8555
      - UPLOADER=ce8806f1ba091a5a54097e275a6d029d1ac3797e41ca8bf8387d385d834cb1e0
      - TNGATEWAY_ACCESS_TOKEN_URL=https://tngateway.testnet.treasurenet.io/oauth/access_token
      - TNGATEWAY_CLIENT_ID=test
      - TNGATEWAY_CLIENT_SECRET=36f028580bb02cc8272a9a020f4200e346e276ae664e45ee80745574e2f5ab80
      - TNGATEWAY_SCOPE=test
      - TNGATEWAY_API_URL=https://tngateway.testnet.treasurenet.io/api
