version: '3'
services:
  treasureNet_productiondatauploader:
    image: treasurenet/productiondatauploader:1.0
    network_mode: "host"
    restart: unless-stopped
    container_name: productiondatauploader
    environment:
      - MONGO_URL=mongodb+srv://treasureNet:Lf7bZVPpArjyru9O@tnclusterm20.a9fcq.mongodb.net/treasureNet?retryWrites=true&w=majority
      - EVM_ENDPOINT=http://node1.testnet.treasurenet.io:8555
      - UPLOADER=0xCef7fccBD38A940DAFAC9F6D2567Fd51C4Da6926
      - SENDER=7838ab5f3f3c0bfe16dd426f4301ee2eae390c8665e9db244fd66601566bec8f
      - TNGATEWAY_ACCESS_TOKEN_URL=https://tngateway.testnet.treasurenet.io/oauth/access_token
      - TNGATEWAY_CLIENT_ID=test
      - TNGATEWAY_CLIENT_SECRET=36f028580bb02cc8272a9a020f4200e346e276ae664e45ee80745574e2f5ab80
      - TNGATEWAY_SCOPE=test
      - TNGATEWAY_API_URL=https://tngateway.testnet.treasurenet.io/api
